name: submodule version

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  doshit:
    runs-on: ubuntu-22.04

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: refactor
        run: mv readme.md addons/IntCut/
      
      - name: remove
        shell: bash
        run: | 
          shopt -s extglob
          rm -rf !(addons|LICENSE)
          ls addons/
      
      - name: movetoroot
        run: mv addons/IntCut/* .

      - name: cleanup
        run: rm -rf addons/
      
      - name: gitshit
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add -A
          git status
          git commit -m "gitshit"
          git status
          ls

      - name: deploy
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.IC_SM_TOK }}
        with:
          branch: submodule-version
