name: submodule version

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  doshit:
    runs-on: ubuntu-22.04

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: refactor
        run: mv readme.md addons/IntCut/
      
      - name: remove
        run: rm -rf .github/ .gitattributes .gitignore icon.svg icon.svg.import project.godot
      
      - name: movetoroot
        run: mv addons/IntCut/* .

      - name: cleanup
        run: rm -rf addons/

      - name: deploy #        uses: peaceiris/actions-gh-pages@v3
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: submodule-version